GET http://localhost:3000/chats/api/find-all/2 
###
POST http://localhost:3000/chats/api/message/2-6
Content-Type: application/json

{
    "members" : [2,6],
    "sender" : 6,
    "message" : "great" 
}