###
//Register a new user
POST  http://localhost:3000/users/api/register
Content-Type: application/json

{
    "firstname":"Dimitris",
    "lastname":"Xristofis",
    "username":"dimxri",
    "email":"dx@gmail.com",
    "password":"1234",
    "address": "Paraskeva 32, Kifisia, 12031",
    "phone": 2105612353,
    "vatNumber": 1115201600287,
    "latitude": 123,
    "longitude": 456
}
###
//Register a new admin
POST  http://localhost:3000/users/api/register
Content-Type: application/json

{
    "firstname":"Konstantinos",
    "lastname":"Theofilis",
    "email":"admin@admin.com",
    "password":"1234"
}
###
POST  http://localhost:3000/users/api/login
Content-Type: application/json

{
    "username": "dimxri",
    "password": "1234"
}
###
GET http://localhost:3000/users/api/2
###
GET http://localhost:3000/users/api
###
PATCH  http://localhost:3000/users/api/status/change/1
Content-Type: application/json

{
    "userStatus": "Decline"
}

###
GET http://localhost:3000/users/api/status/pending
###