###
POST  http://localhost:3000/users/api/register
Content-Type: application/json

{
    "firstname":"Dimitri",
    "lastname":"Xrist",
    "email":"dx@gmail.com",
    "password":"1234",
    "mobile": 432345
}
###
GET http://localhost:3000/users/api/1
###
GET http://localhost:3000/users/api
###
POST  http://localhost:3000/users/api/login
Content-Type: application/json

{
    "email": "kt@gmail.com",
    "password": "1234"
}

###
PATCH  http://localhost:3000/users/api/1
Content-Type: application/json

{
    "firstname": "Μανος"
}
###